spring.application.name=taskmanager-spring
spring.thymeleaf.cache=false

spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager_db
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver